[package]
name = "aoc-2022-16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
kdam = "0.4.1"
regex = "1.9.5"
